### ISSUE TITLE
SIIM-ACR Pneumothorax dataset in fine-tuning of segmentation

### ISSUE THREAD

**Issue by realmadridchenwentao** [RL4M/MRM-pytorch#2]
Hi, thank you for your excellent work! 
In Part 5 in README, how is the SIIM-ACR Pneumothorax data from Kaggle mapped to the code you used? The name (ID) of the downloaded data from Kaggle link are like `ID_0a0adf93f`, while in this repo the name (ID) of the downloaded data are like `1.2.276.0.7230010.3.1.4.8323329.1608.1517875168.577144`. I was wondering if there is any other way to get this part of the dataset (maybe only the stage1 data?). Thanks.

**Comment by DopamineLcy** [comment]
Please use the download script to get the dataset (https://www.kaggle.com/competitions/siim-acr-pneumothorax-segmentation/data?select=download_images.py). Only the stage1 data.

**Comment by zoule41** [comment]
> 请使用下载脚本获取数据集 （https://www.kaggle.com/competitions/siim-acr-pneumothorax-segmentation/data?select=download_images.py）。仅 stage1 数据。
Hello, the official website no longer provides the complete SIIM dataset. May I ask if you can share it with me? My email 283698626@qq.com Thank you
